workflows:
  base-workflow: &base
    name: Base Workflow
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment: &base_environment
      android_signing:
        - Graded
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.NightDreamGames.Gradely
      groups:
        - gh-auth
        - playstore-auth
      vars:
        PACKAGE_NAME: "com.NightDreamGames.Grade.ly"
        APP_ID: 6444681284
      flutter: stable
      xcode: latest
      cocoapods: default
    integrations:
      app_store_connect: NightDream Games
    scripts: &base_scripts
      - name: Remove problematic folders
        script: |
          rm -rf .flutter
          rm -rf fastlane
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release \
            --build-number=$(($PROJECT_BUILD_NUMBER + 50))
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA with Flutter
        script: |
          flutter build ipa --release \
            --build-number=$(($PROJECT_BUILD_NUMBER + 50)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/apk/release/*.apk
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing: &base_publishing
      email:
        recipients:
          - build@nightdreamgames.com
        notify:
          success: false
          failure: true
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
  release-workflow:
    <<: *base
    name: Release Workflow
    scripts:
      - name: Set up environment variables
        script: |
          file=$(cat pubspec.yaml)
          fullVersion=$(echo | grep -i -e "version: " pubspec.yaml)
          echo "BUILD_NAME=$(echo $fullVersion | cut -d " " -f 2 | cut -d "+" -f 1)" >> $CM_ENV
          echo "BUILD_NUMBER=$(($PROJECT_BUILD_NUMBER+50))" >> $CM_ENV

          echo "$fullVersion BUILD_NAME: ${BUILD_NAME} BUILD_NUMBER: ${BUILD_NUMBER}"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Automatic versioning
        script: |
          #!/usr/bin/env zsh

          perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.($ENV{BUILD_NUMBER})/e' pubspec.yaml
          git submodule foreach git pull origin stable

          files=("release_notes_en-GB.txt" "release_notes_fr-FR.txt" "release_notes_de-DE.txt")

          for file in ${files[@]}; do
            { echo "Version ${BUILD_NAME}:"; cat release_notes/${file}; } >${file}
            cat $file
            echo; echo
          done

          mkdir -p fastlane/metadata/android/en-US/changelogs
          mkdir -p fastlane/metadata/android/fr-FR/changelogs
          mkdir -p fastlane/metadata/android/de-DE/changelogs

          cp release_notes_en-GB.txt fastlane/metadata/android/en-US/changelogs/$BUILD_NUMBER.txt
          cp release_notes_fr-FR.txt fastlane/metadata/android/fr-FR/changelogs/$BUILD_NUMBER.txt
          cp release_notes_de-DE.txt fastlane/metadata/android/de-DE/changelogs/$BUILD_NUMBER.txt
      - name: Commit versioning changes
        script: |
          gh auth setup-git
          git add --all
          git commit -m "Versioning changes for ${BUILD_NAME}"
          git push
      - name: Remove problematic folders
        script: |
          rm -rf .flutter
          rm -rf fastlane
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release \
            --build-number=$BUILD_NUMBER
      - name: Build APK with Flutter
        script: |
          flutter build apk --release \
            --build-number=$BUILD_NUMBER
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA with Flutter
        script: |
          flutter build ipa --release \
            --build-number=$(($PROJECT_BUILD_NUMBER + 50)) \
            --export-options-plist=/Users/builder/export_options.plist
      - name: Publish to GitHub
        script: |
          #!/usr/bin/env zsh

          mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/graded-${BUILD_NAME}.apk
          mv build/ios/ipa/Graded.ipa build/ios/ipa/graded-${BUILD_NAME}.ipa

          gh release create "${BUILD_NAME}" \
            --title "${BUILD_NAME}" \
            --notes-file release_notes/release_notes_gh.txt \
            build/app/outputs/apk/release/graded-${BUILD_NAME}.apk \
            build/ios/ipa/graded-${BUILD_NAME}.ipa
  #  publishing:
  #    <<: *base_publishing
  #    google_play:
  #      credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
  #      track: production
  #      submit_as_draft: false
  #    app_store_connect:
  #      auth: integration
  #      submit_to_testflight: false
  #      submit_to_app_store: true
  #      cancel_previous_submissions: true
  #      release_type: AFTER_APPROVAL
  internal-workflow:
    <<: *base
    name: Internal Workflow
    publishing:
      <<: *base_publishing
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: "internal"
        submit_as_draft: false
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false
