name: graded
description: Track and manage your school grades with ease
publish_to: "none"
version: 2.2.1+143

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.3
  diacritic: ^0.1.3
  dynamic_color: ^1.4.0
  intl: ^0.17.0
  path_provider: ^2.0.2
  provider: ^6.0.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  xml: ^6.1.0
  device_info_plus: ^8.0.0
  flutter_displaymode: ^0.5.0
  flutter_file_dialog: ^3.0.0
  package_info_plus: ^3.0.1
  showcaseview: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.22.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.13.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  assets:
    - assets/class_data/

flutter_intl:
  enabled: true
  class_name: TranslationsClass
  main_locale: en
  arb_dir: lib/localization/l10n
  output_dir: lib/localization/generated

flutter_icons:
  android: true
  ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
  image_path: "assets/icons/GRADED-Icon.png"
  image_path_android: "assets/icons/GRADED-Icon-RoundRect.png"
  adaptive_icon_foreground: "assets/icons/GRADED-Icon-Foreground-Large.png"
  adaptive_icon_background: "#62A9E1"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FDFCFF"
  color_dark: "#1A1C1E"
  image: assets/icons/GRADED-Icon-RoundRect.png
  android_12:
    color: "#FDFCFF"
    color_dark: "#1A1C1E"
    image: assets/icons/GRADED-Icon-Foreground-Large.png
    icon_background_color: "#62A9E1"
  android: true
  ios: true
  web: false

import_path_converter:
  relative: true

import_sorter:
  ignored_files:
    - \/lib\\localization\\.*
