name: gradely
description: A clean and open-source app to track and manage your school grades.
publish_to: "none"
version: 2.0.2+43

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sprintf: ^7.0.0
  flutter_displaymode: ^0.4.0
  cupertino_icons: ^1.0.3
  diacritic: ^0.1.3
  shared_preferences: ^2.0.13
  path_provider: ^2.0.2
  provider: ^6.0.0
  package_info_plus: ^3.0.1
  customizable_space_bar: ^0.2.0
  url_launcher: ^6.0.20
  xml: ^5.0.0
  dynamic_color: ^1.4.0
  excel: ^2.0.0-null-safety-3
  animations: ^2.0.0
  tuple: ^2.0.1
  collection: ^1.16.0
  flutter_native_splash: ^2.2.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flappy_translator: ^2.0.0-nullsafety.3
  flutter_launcher_icons: ^0.11.0
  import_sorter: ^4.6.0

flutter_icons:
  android: true
  min_sdk_android: 21
  ios: true
  adaptive_icon_background: "#62A9E1"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true

flappy_translator:
  input_file_path: "assets/Localizations.xlsx"
  output_dir: "lib/Translations"
  file_name: "translations"
  class_name: "Translations"
  depend_on_context: false

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  assets:
    - assets/

flutter_native_splash:
  color: "#fdfcff"
  color_dark: "#1a1c1e"
  image: assets/icons/icon-round.png
  android_12:
    color: "#fdfcff"
    color_dark: "#1a1c1e"
    image: assets/icons/icon-large.png
    icon_background_color: "#62a9e1"
    icon_background_color_dark: "#62a9e1"
  android: true
  ios: true
  web: false
