name: graded
description: A clean and open-source app to track and manage your school grades.
publish_to: "none"
version: 2.0.5+51

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_displaymode: ^0.5.0
  cupertino_icons: ^1.0.3
  diacritic: ^0.1.3
  shared_preferences: ^2.0.13
  path_provider: ^2.0.2
  provider: ^6.0.0
  package_info_plus: ^3.0.1
  url_launcher: ^6.0.20
  xml: ^6.1.0
  dynamic_color: ^1.4.0
  excel: ^2.0.1
  animations: ^2.0.0
  collection: ^1.16.0
  flutter_exit_app: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flappy_translator: ^2.0.0-nullsafety.3
  flutter_launcher_icons: ^0.11.0
  import_sorter: ^4.6.0
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  assets:
    - assets/class_data/

flappy_translator:
  input_file_path: "assets/Localizations.xlsx"
  output_dir: "lib/Translations"
  file_name: "translations"
  class_name: "Translations"
  depend_on_context: false

flutter_icons:
  android: true
  ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
  image_path: "assets/icons/GRADED-Icon.png"
  image_path_android: "assets/icons/GRADED-Icon-RoundRect.png"
  adaptive_icon_foreground: "assets/icons/GRADED-Icon-Foreground-Large.png"
  adaptive_icon_background: "#62A9E1"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FDFCFF"
  color_dark: "#1A1C1E"
  image: assets/icons/GRADED-Icon-RoundRect.png
  android_12:
    color: "#FDFCFF"
    color_dark: "#1A1C1E"
    image: assets/icons/GRADED-Icon-Foreground-Large.png
    icon_background_color: "#62A9E1"
  android: true
  ios: true
  web: false
