name: gradely
description: A clean and open-source app to track and manage your school grades.
publish_to: "none"
version: 2.0.0+36

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sprintf: ^7.0.0
  flutter_displaymode: ^0.4.0
  cupertino_icons: ^1.0.3
  diacritic: ^0.1.3
  shared_preferences: ^2.0.13
  path_provider: ^2.0.2
  provider: ^6.0.0
  page_transition: ^2.0.5
  package_info_plus: ^3.0.1
  customizable_space_bar: ^0.2.0
  url_launcher: ^6.0.20
  xml: ^5.0.0
  dynamic_color: ^1.4.0
  excel: ^2.0.0-null-safety-3

dev_dependencies:
  flutter_lints: ^2.0.0
  flappy_translator:
    path: C:/Dev/Libraries/Flutter/FlappyTranslator
  flutter_launcher_icons: ^0.10.0
  integration_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#62A9E1"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true

flappy_translator:
  input_file_path: "assets/Localizations.xlsx"
  output_dir: "lib/Translation"
  file_name: "translations"
  class_name: "Translations"
  depend_on_context: false

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
  assets:
    - assets/
