# .github/workflows/bump_submodule.yaml

name: Bump Flutter submodule

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  bump_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump Flutter submodule
        run: |
          git submodule update --remote --init --recursive
          git add .flutter
          git commit -m "Upgrade submodule"
