# .github/workflows/bump_submodule.yaml

name: Bump Flutter submodule

on:
  workflow_dispatch:
  workflow_call:

jobs:
  bump_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "Faucon"
          git config --global user.email "49079695+FauconSpartiate@users.noreply.github.com"

      - name: Save Flutter version
        run: |
          git submodule update --init
          echo "OLD_FLUTTER_VERSION=$(.flutter/bin/flutter --version)" >> $GITHUB_ENV

      - name: Bump Flutter submodule
        run: |
          git submodule update --remote --init

      - name: Commit changes
        run: |
          git add .flutter
          if ! git diff-index --quiet HEAD; then
            git commit -m "Bump Flutter submodule\n\nFlutter version: ${{ env.OLD_FLUTTER_VERSION }} -> $(.flutter/bin/flutter --version)"
            git push origin main
          fi

      - name: Print Flutter version
        run: .flutter/bin/flutter --version
