# .github/workflows/bump_submodule.yaml

name: Bump Flutter submodule

on:
  push:
    branches:
      - "*"
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  bump_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "49079695+FauconSpartiate@users.noreply.github.com"
          git config --global user.name "Faucon"

      - name: Bump Flutter submodule
        run: |
          git submodule update --remote --init --recursive
          git add .flutter
          git commit -m "Upgrade submodule"
          git push
